language: node_js
node_js:
  - 10
cache: yarn
install:
  - yarn
script:
  - yarn build
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git config --global user.name $GH_EMAIL
  - git config --global user.email $GH_NAME
  - git add -A
  - git commit -m 'deploy gh-pages'
  - git push --quiet --force https://$GH_TOKEN@$GH_REF master:$P_BRANCH